server:
  port: 8084
  

spring:
  application:
    name: API-GATEWAY
    
  cloud:
    gateway:
       routes:
        - id : USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path= /users/**
        - id : RECHARGE-SERVICE
          uri: lb://RECHARGE-SERVICE
          predicates:
            - Path= /recharge-service/**
        - id : CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path= /customer/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  